# k8s/django-migrate-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: stephenristow/pawsport-app:latest 
          command: ["python", "manage.py", "migrate"]
          env:
            - name: DATABASE_HOST
              value: "mysql"
            - name: DATABASE_NAME
              value: "pawsportdb"
            - name: DATABASE_USER
              value: "pawsportuser"
            - name: DATABASE_PASSWORD
              value: "pawsportpass"
      restartPolicy: Never
  backoffLimit: 2
