
# k8s/mysql.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: pawsportdb
            - name: MYSQL_ROOT_PASSWORD
              value: secretpassword
            - name: MYSQL_USER
              value: pawsportuser
            - name: MYSQL_PASSWORD
              value: pawsportpass
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: initdb
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: initdb
          configMap:
            name: mysql-initdb-config  
        - name: mysql-data 
          persistentVolumeClaim:
            claimName: mysql-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
